[package]
name = "webview_deno"
version = "0.4.4"
authors = ["Elias Sjögreen", "Filippo Rossi"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
deno_core = "0.49.0"
webview-sys = { git = "https://github.com/tauri-apps/web-view.git" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
futures = "0.3.5"

[features]
default = ["webview-sys/edge"]
