[package]
name = "deno_webview"
version = "0.1.0"
authors = ["Elias Sjögreen <eliassjogreen1@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
futures = "0.3.4"
deno_core = "0.35.0"
web-view = "0.6.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
