[package]
name = "deno_webview"
version = "0.3.2"
authors = ["Elias Sjögreen <eliassjogreen1@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
deno_core = "0.40.0"
webview-sys = "0.5.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.51"
futures = "0.3.4"

[features]
default = ["webview-sys/edge"]
