[package]
name = "deno_webview"
version = "0.4.2"
authors = ["Elias Sjögreen <eliassjogreen1@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
deno_core = "0.47.1"
webview-sys = { git = "https://github.com/tauri-apps/web-view.git" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
futures = "0.3.5"

[features]
default = ["webview-sys/edge"]
