[package]
name = "deno_webview"
version = "0.1.1"
authors = ["Elias Sjögreen <eliassjogreen1@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
deno_core = "0.35.0"
webview-sys = "0.4.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[features]
default = ["webview-sys/edge"]
